{{- if ne .Values.operator.metricsBindAddress "0" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-operator.fullname" . }}-metrics
  labels:
    {{- include "ingress-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ingress-operator.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-operator.fullname" . }}-health
  labels:
    {{- include "ingress-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "ingress-operator.selectorLabels" . | nindent 4 }}
